### ISSUE TITLE
Postgresql install hook fails when deployed via GUI

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#1530]
When deploying the promulgated postgresql charm via the GUI it it will fail in the install hook but it will be successfully deployed if deployed via the CLI.

```
2016-04-08 20:39:19 INFO install     config[key] = config[key].lower()  # Rewrite to lower case.
2016-04-08 20:39:19 INFO install KeyError: 'version'
```
Line in error: 
  http://bazaar.launchpad.net/~charmers/charms/trusty/postgresql/trunk/view/head:/hooks/service.py#L53

GUI RPC Call: 
  https://gist.github.com/hatched/daf07c69cbbcb5dd90b0b4426f6ed4ef

Charm config output:
```
  version:
    default: true
    description: |
      Version of PostgreSQL that we want to install. Supported versions are "9.1", "9.2", "9.3" & "9.4". The default version for the deployed Ubuntu release is used when the version is not specified.
    type: string
    value: ""
```

A possible rational proposed by @frankban is that Juju unsets the service option if an empty value is passed to `Service.Deploy` and because the GUI always sends all values, even if they are empty, this is likely causing the 'version' value to not exist when the charm expects it to be there.
