### ISSUE TITLE
juju gui doesn't honor all config values from a bundle

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#2149]
Originally filed: https://bugs.launchpad.net/juju-gui/+bug/1635340 
See above for assets.

Loading the landscape-dense-maas bundle [1] in the gui [2] shows an incorrect value for the services option in the haproxy configuration. These leads to a failure to deploy haproxy and a broken deployment of landscape.

The bundle defines haproxy as:

```
    haproxy:
        charm: cs:trusty/haproxy-16
        to:
            - lxc:0
        expose: True
        num_units: 1
        options:
            enable_monitoring: True
            monitoring_allowed_cidr: "0.0.0.0/0"
            monitoring_password: "haproxy"
            default_timeouts: "queue 60000, connect 5000, client 120000, server 120000"
            # Don't deploy default haproxy service on port 80
            services: ""
            source: backports
            ssl_cert: SELFSIGNED
        annotations:
            "gui-x": "1200"
            "gui-y": "120"
```

The juju-gui shows a haproxy.services value of:
- service_name: haproxy_service
  service_host: "0.0.0.0"
  service_port: 80
  service_options: [balance leastconn, cookie SRVNAME insert]
  server_options: maxconn 100 cookie S{i} check

This matches the haproxy charm's default value, not what the bundle is setting, which is the expected value. I was only able to test this using the demo at [2] to see the unexpected values. But this fails for others (logs attached) when actually deploying.

[1] - cs:bundle/landscape-dense-maas-1
[2] - https://demo.jujucharms.com/
