### ISSUE TITLE
Export from 2.0.2 GUI creates incorrect boolean values in YAML

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#2324]
From https://bugs.launchpad.net/juju/+bug/1649848:

This is a bundle exported from a basic Kubernetes setup. Note the "falsetrue" and "truetrue" boolean values; that can't be right.

```yaml
series: xenial
applications:
  etcd:
    charm: "cs:~containers/etcd-17"
    num_units: 1
    annotations:
      "gui-x": "1825"
      "gui-y": "741"
    to:
      - "0"
  "kubernetes-worker":
    charm: "cs:~containers/kubernetes-worker-11"
    num_units: 1
    options:
      "enable-cgroups": falsetrue
      ingress: truetrue
      install_from_upstream: falsetrue
    annotations:
      "gui-x": "1430"
      "gui-y": "646"
    to:
      - "1"
  "kubernetes-master":
    charm: "cs:~containers/kubernetes-master-8"
    num_units: 1
    options:
      "enable-dashboard-addons": truetrue
    annotations:
      "gui-x": "640"
      "gui-y": "456"
    to:
      - "0"
  flannel:
    charm: "cs:~containers/flannel-6"
    annotations:
      "gui-x": "2220"
      "gui-y": "836"
  easyrsa:
    charm: "cs:~containers/easyrsa-3"
    num_units: 1
    annotations:
      "gui-x": "1035"
      "gui-y": "551"
    to:
      - "lxd:kubernetes-master/0"
relations:
  - - "kubernetes-master:sdn-plugin"
    - "flannel:host"
  - - "kubernetes-master:kube-api-endpoint"
    - "kubernetes-worker:kube-api-endpoint"
  - - "kubernetes-master:cluster-dns"
    - "kubernetes-worker:kube-dns"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "flannel:etcd"
    - "etcd:db"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "kubernetes-worker:sdn-plugin"
    - "flannel:host"
machines:
  "0":
    series: xenial
    constraints: "arch=amd64 cpu-cores=4 mem=7983"
  "1":
    series: xenial
    constraints: "arch=amd64 cpu-cores=2 mem=3951"
```
