### ISSUE TITLE
Charm left in initial position doesn't have gui annotations

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2329]
The GUI location annotations for a charm left in its initial position are not saved in the resulting bundle when exported.

*Note that "no gui annotations" is a warning for `charm proof` which means that `bundletester` will fail.*

1. Go to demo.jujucharms.com
2. Add the wordpress charm and **make sure to not move the charm from its initial position**
3. commit the changes and click "export bundle".

now: 

```yaml
applications: 
  wordpress: 
    charm: "cs:trusty/wordpress-4"
    num_units: 1
    to: 
      - "0"
```

want: 

```yaml
applications: 
  limeds: 
    charm: "cs:trusty/wordpress-4"
    num_units: 1
    annotations: 
      "gui-x": 0
      "gui-y": 0
    to: 
      - "0"
```
