### ISSUE TITLE
charm config lost when deploying bundle in jaas

### ISSUE THREAD

**Issue by kwmonroe** [juju/juju-gui#3045]
I have specific configuration for the `spark` charm as part of the `hadoop-spark` bundle:

```yaml
...
  spark:
    charm: "cs:xenial/spark-46"
    constraints: "mem=7G root-disk=32G"
    num_units: 1
    options:
      spark_execution_mode: "yarn-client"
...
```

When logged into the store, i click "Add to model" from this page:  https://jujucharms.com/hadoop-spark.  I confirm the spark config looks right (`spark_execution_mode == yarn-client`):

![screen shot 2017-07-03 at 11 54 57 am](https://user-images.githubusercontent.com/4576822/27801964-7db084b4-5fe6-11e7-8fb6-ac5de8cec11e.png)

I then click "Deploy changes (56)", choose a cloud, paste my ssh key, and click "Deploy".  I'm returned to the canvas, but my `spark` config is no longer correct (`spark_execution_mode == standalone`):

![screen shot 2017-07-03 at 11 57 19 am](https://user-images.githubusercontent.com/4576822/27802009-cea61a46-5fe6-11e7-91e6-e40dbe00d7b8.png)
